---
- name: play-4
  hosts: all
  become: yes

  tasks:

  - name: create directory project
    file:
      path: /Project
      state: directory

  - name: create directory Ansible
    file:
      path: /Ansible
      state: directory
